CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE TABLE "User" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" integer NOT NULL,
        "Division" text NOT NULL,
        "Points" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_User" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE TABLE "Challenge" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Prize" numeric NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "CreatedById" integer NOT NULL,
        CONSTRAINT "PK_Challenge" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Challenge_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE TABLE "StrategicGuideline" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Priority" integer NOT NULL,
        "Category" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedByUserId" integer NOT NULL,
        "CreatedById" integer NOT NULL,
        CONSTRAINT "PK_StrategicGuideline" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StrategicGuideline_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE TABLE "Idea" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Division" text NOT NULL,
        "Status" integer NOT NULL,
        "ImpactScore" integer NOT NULL,
        "FeasibilityScore" integer NOT NULL,
        "AlignmentScore" integer NOT NULL,
        "EvidenceUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UserId" integer NOT NULL,
        "ChallengId" integer,
        "ChallengeId" integer,
        CONSTRAINT "PK_Idea" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Idea_Challenge_ChallengeId" FOREIGN KEY ("ChallengeId") REFERENCES "Challenge" ("Id"),
        CONSTRAINT "FK_Idea_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE TABLE "Project" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Division" text NOT NULL,
        "Status" integer NOT NULL,
        "Stage" integer NOT NULL,
        "Investiment" numeric NOT NULL,
        "FinancialReturn" numeric NOT NULL,
        "ProductivityGain" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "Deadline" timestamp with time zone NOT NULL,
        "ProgressPercent" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "ManagerId" integer NOT NULL,
        "IdeaId" integer,
        CONSTRAINT "PK_Project" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Project_Idea_IdeaId" FOREIGN KEY ("IdeaId") REFERENCES "Idea" ("Id"),
        CONSTRAINT "FK_Project_User_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_Challenge_CreatedById" ON "Challenge" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_Idea_ChallengeId" ON "Idea" ("ChallengeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_Idea_UserId" ON "Idea" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_Project_IdeaId" ON "Project" ("IdeaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_Project_ManagerId" ON "Project" ("ManagerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    CREATE INDEX "IX_StrategicGuideline_CreatedById" ON "StrategicGuideline" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185152_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260502185152_InitialCreate', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185528_FixIdeaChallengeId') THEN
    ALTER TABLE "Idea" DROP COLUMN "ChallengId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502185528_FixIdeaChallengeId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260502185528_FixIdeaChallengeId', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Challenge" DROP CONSTRAINT "FK_Challenge_User_CreatedById";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Idea" DROP CONSTRAINT "FK_Idea_Challenge_ChallengeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Idea" DROP CONSTRAINT "FK_Idea_User_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Project" DROP CONSTRAINT "FK_Project_Idea_IdeaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Project" DROP CONSTRAINT "FK_Project_User_ManagerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "StrategicGuideline" DROP CONSTRAINT "FK_StrategicGuideline_User_CreatedById";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "User" DROP CONSTRAINT "PK_User";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "StrategicGuideline" DROP CONSTRAINT "PK_StrategicGuideline";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Project" DROP CONSTRAINT "PK_Project";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Idea" DROP CONSTRAINT "PK_Idea";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Challenge" DROP CONSTRAINT "PK_Challenge";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "User" RENAME TO "Users";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "StrategicGuideline" RENAME TO "StrategicGuidelines";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Project" RENAME TO "Projects";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Idea" RENAME TO "Ideas";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Challenge" RENAME TO "Challenges";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_StrategicGuideline_CreatedById" RENAME TO "IX_StrategicGuidelines_CreatedById";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_Project_ManagerId" RENAME TO "IX_Projects_ManagerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_Project_IdeaId" RENAME TO "IX_Projects_IdeaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_Idea_UserId" RENAME TO "IX_Ideas_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_Idea_ChallengeId" RENAME TO "IX_Ideas_ChallengeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER INDEX "IX_Challenge_CreatedById" RENAME TO "IX_Challenges_CreatedById";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Users" ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "StrategicGuidelines" ADD CONSTRAINT "PK_StrategicGuidelines" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Projects" ADD CONSTRAINT "PK_Projects" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Ideas" ADD CONSTRAINT "PK_Ideas" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Challenges" ADD CONSTRAINT "PK_Challenges" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Challenges" ADD CONSTRAINT "FK_Challenges_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Ideas" ADD CONSTRAINT "FK_Ideas_Challenges_ChallengeId" FOREIGN KEY ("ChallengeId") REFERENCES "Challenges" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Ideas" ADD CONSTRAINT "FK_Ideas_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Projects" ADD CONSTRAINT "FK_Projects_Ideas_IdeaId" FOREIGN KEY ("IdeaId") REFERENCES "Ideas" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "Projects" ADD CONSTRAINT "FK_Projects_Users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    ALTER TABLE "StrategicGuidelines" ADD CONSTRAINT "FK_StrategicGuidelines_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503182049_SyncModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260503182049_SyncModel', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503203352_FixUserRoleEnum') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260503203352_FixUserRoleEnum', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505111931_FixTyposInvestmentProductivityGain') THEN
    ALTER TABLE "Projects" RENAME COLUMN "Investiment" TO "Investment";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505111931_FixTyposInvestmentProductivityGain') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505111931_FixTyposInvestmentProductivityGain', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505141335_FixCreatedByForeignKey') THEN

                    ALTER TABLE "StrategicGuidelines"
                        DROP CONSTRAINT IF EXISTS "FK_StrategicGuidelines_Users_CreatedById";

                    ALTER TABLE "StrategicGuidelines"
                        RENAME COLUMN "CreatedById" TO "CreatedByUserId";

                    ALTER TABLE "StrategicGuidelines"
                        ADD CONSTRAINT "FK_StrategicGuidelines_Users_CreatedByUserId"
                        FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE CASCADE;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505141335_FixCreatedByForeignKey') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505141335_FixCreatedByForeignKey', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "Challenges" DROP CONSTRAINT "FK_Challenges_Users_CreatedByUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "StrategicGuidelines" DROP CONSTRAINT "FK_StrategicGuidelines_Users_CreatedByUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    DROP INDEX "IX_StrategicGuidelines_CreatedByUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    DROP INDEX "IX_Challenges_CreatedByUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "StrategicGuidelines" ADD "CreatedById" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "Challenges" ADD "CreatedById" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    CREATE INDEX "IX_StrategicGuidelines_CreatedById" ON "StrategicGuidelines" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    CREATE INDEX "IX_Challenges_CreatedById" ON "Challenges" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "Challenges" ADD CONSTRAINT "FK_Challenges_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    ALTER TABLE "StrategicGuidelines" ADD CONSTRAINT "FK_StrategicGuidelines_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505170159_SyncModelSnapshot') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505170159_SyncModelSnapshot', '9.0.4');
    END IF;
END $EF$;
COMMIT;

